[pytest]
testpaths = tests
asyncio_mode = auto
filterwarnings =
    ignore:builtin type SwigPyPacked:DeprecationWarning
    ignore:builtin type SwigPyObject:DeprecationWarning
    ignore:builtin type swigvarlink:DeprecationWarning
