# yaml

components_manager:
    coro_pool:
        initial_size: 500             # Preallocate 500 coroutines at startup.
        max_size: 1000                # Do not keep more than 1000 preallocated coroutines.

    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.
            thread_name: main-worker  # OS will show the threads of this task processor with 'main-worker' prefix.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            thread_name: fs-worker
            worker_threads: $worker-fs-threads

        monitor-task-processor:       # for monitoring
            thread_name: mon-worker
            worker_threads: 1

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
            listener-monitor:
                # Listen on 8086 port for developer/utility requests
                port: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: monitor-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '/tmp/logs/working_day/log.txt'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        tracer:                              # Component that helps to trace execution times and requests in logs.
            service-name: working_day   # "You know. You all know exactly who I am. Say my name. " (c)

        dynamic-config:                      # Dynamic config storage options, do nothing
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is_testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: monitor-task-processor

        secdist: {}
        default-secdist-provider:
            config: configs/secdist.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        handler-v1-employee-add:
            path: /v1/employee/add           
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin
                  - superuser

        handler-v1-employee-add-head:
            path: /v1/employee/add-head           
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin

        handler-v1-employee-info:
            path: /v1/employee/info          
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-employee-remove:
            path: /v1/employee/remove          
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin

        handler-v1-employees:
            path: /v1/employees         
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-profile-upload-photo:
            path: /v1/profile/upload-photo         
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user
        
        handler-v1-profile-edit:
            path: /v1/profile/edit
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-authorize:
            path: /v1/authorize
            method: POST
            task_processor: main-task-processor

        handler-v1-abscence-request:
            path: /v1/abscence/request
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-abscence-verdict:
            path: /v1/abscence/verdict
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user
            pyservice-url: 'http://python-service:3000/document/generate'

        handler-v1-notifications:
            path: /v1/notifications
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-actions:
            path: /v1/actions
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-documents-vacation:
            path: /v1/documents/vacation
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-attendance-add:
            path: /v1/attendance/add
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - manager

        handler-v1-abscence-split:
            path: /v1/abscence/split
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-abscence-reschedule:
            path: /v1/abscence/reschedule
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-payments-add-bulk:
            path: /v1/payments/add-bulk
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin # TODO: make robot

        handler-v1-payments:
            path: /v1/payments
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-clear-tasks:
            path: /v1/clear-tasks
            method: POST
            task_processor: main-task-processor

        handler-v1-search-basic:
            path: /v1/search/basic
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-search-suggest:
          path: /v1/search/suggest
          method: POST
          task_processor: main-task-processor
          auth:
              types:
                - bearer
              scopes:
                - user

        handler-v1-attendance-list-all:
            path: /v1/attendance/list-all
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin
                  - manager

        handler-v1-documents-upload:
            path: /v1/documents/upload
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin

        handler-v1-documents-send:
            path: /v1/documents/send
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin

        handler-v1-documents-list:
            path: /v1/documents/list
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user
        
        handler-v1-documents-download:
            path: /v1/documents/download
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-search-full:
            path: /v1/search/full
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user

        handler-v1-documents-sign:
            path: /v1/documents/sign
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - user
            pyservice-url: 'http://python-service:3000/document/sign'

        handler-v1-documents-list-all:
            path: /v1/documents/list-all
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin

        handler-v1-documents-get-signs:
            path: /v1/documents/get-signs
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin

        handler-v1-inventory-add:
            path: /v1/inventory/add
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - admin

        handler-v1-superuser-company-add:
            path: /v1/superuser/company/add
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                scopes:
                  - superuser
            db: $dbconnection

        handler-implicit-http-options:
            as_fallback: implicit-http-options
            method: OPTIONS
            task_processor: main-task-processor
            throttling_enabled: false

        key-value:
            dbconnection: $dbconnection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true

        auth-pg-cache:
            pgcomponent: key-value
            update-types: full-and-incremental
            full-update-interval: 1h
            update-interval: 10m
            update-correction: 0
            chunk-size: 0

        dns-client:
            fs-task-processor: fs-task-processor
