openapi: 3.0.0
info:
    description: Working Day Service
    title: Working Day Service
    version: '1.0'

servers:
  - url: http://84.201.137.230:8080
    description: production

paths:
# |--------------| AUTH-PROFILE |--------------|


    /v1/profile/upload-photo:
        $ref: "./path/auth-profile.yaml#/UploadPhoto"

    /v1/profile/edit:
        $ref: "./path/auth-profile.yaml#/Edit"

    /v1/authorize:
        $ref: "./path/auth-profile.yaml#/Auth"


# |--------------| AUTH-PROFILE |--------------|
# |--------------| DOCUMENT |--------------|


    /v1/documents/vacation:
        $ref: "./path/document.yaml#/GenerateVacationDocument"

    /v1/documents/upload:
        $ref: "./path/document.yaml#/DocumentUpload"

    /v1/documents/send:
        $ref: "./path/document.yaml#/SendDocument"

    /v1/documents/list:
        $ref: "./path/document.yaml#/DocumentsList"

    /v1/documents/download:
        $ref: "./path/document.yaml#/DownloadDocument"

    /v1/documents/list-all:
        $ref: "./path/document.yaml#/DocumentsAllList"

    /v1/documents/get-signs:
        $ref: "./path/document.yaml#/EmployeesSignedDocoment"

    /v1/documents/sign:
        $ref: "./path/document.yaml#/SignDocument"

    /v1/documents/chain/update:
        $ref: "./path/document.yaml#/DocumentStatusUpdate"

    /v1/documents/chain/add:
        $ref: "./path/document.yaml#/AddChainDocument"


# |--------------| DOCUMENT |--------------|
# |--------------| EMPLOYEE |--------------|


    /v1/employees:
        $ref: "./path/employee.yaml#/ListEmployees"

    /v1/employee/add:
        $ref: "./path/employee.yaml#/AddEmployee"

    /v1/employee/add-head:
        $ref: "./path/employee.yaml#/AddEmployee"

    /v1/employee/remove:
        $ref: "./path/employee.yaml#/RemoveEmployee"

    /v1/employee/info:
        $ref: "./path/employee.yaml#/EmployeeInfo"


# |--------------| EMPLOYEE |--------------|
# |--------------| MESSENGER |--------------|


    /v1/messenger/list-chats:
        $ref: "./path/messenger.yaml#/GetChatList"

    /v1/messenger/create-chat:
        $ref: "./path/messenger.yaml#/CreateChat"

    /v1/messenger/recent-messages:
        $ref: "./path/messenger.yaml#/GetRecentMessages"


# |--------------| MESSENGER |--------------|
# |--------------| NOTIFICATION |--------------|


    /v1/notifications:
        $ref: "./path/notification.yaml#/NotificationList"

    /v1/actions:
        $ref: "./path/notification.yaml#/ActionsList"


# |--------------| NOTIFICATION |--------------|
# |--------------| OTHER |--------------|


    /v1/superuser/company/add:
        $ref: "./path/other.yaml#/AddCompany"

    /v1/inventory/add:
        $ref: "./path/other.yaml#/AddInventoryItem"

    /v1/clear-tasks:
        $ref: "./path/other.yaml#/ClearTasksQueue"


# |--------------| OTHER |--------------|
# |--------------| PAYMENT-ATTENDANCE |--------------|


    /v1/abscence/request:
        $ref: "./path/payment-attendance.yaml#/AbscenceRequest"

    /v1/abscence/verdict:
        $ref: "./path/payment-attendance.yaml#/AbscenceVerdict"

    /v1/abscence/split:
        $ref: "./path/payment-attendance.yaml#/AbscenceSplit"

    /v1/abscence/reschedule:
        $ref: "./path/payment-attendance.yaml#/AbscenceReschedule"

    /v1/attendance/add:
        $ref: "./path/payment-attendance.yaml#/AddAttendance"

    /v1/payments/add-bulk:
        $ref: "./path/payment-attendance.yaml#/AddBult"

    /v1/payments:
        $ref: "./path/payment-attendance.yaml#/GetPayment"

    /v1/attendance/list-all:
        $ref: "./path/payment-attendance.yaml#/AttendancesList"


# |--------------| PAYMENT-ATTENDANCE |--------------|
# |--------------| SEARCH |--------------|


    /v1/search/basic:
        $ref: "./path/search.yaml#/SearchBasic"

    /v1/search/full:
        $ref: "./path/search.yaml#/SearchMultiple"

    /v1/search/suggest:
        $ref: "./path/search.yaml#/SearchSuggest"


# |--------------| SEARCH |--------------|
# |--------------| TRACKER |--------------|


    /v1/tracker/projects/add:
        $ref: "./path/tracker.yaml#/TrackerAddProject"

    /v1/tracker/projects/list:
        $ref: "./path/tracker.yaml#/TrackerProjectsList"

    /v1/tracker/tasks/add:
        $ref: "./path/tracker.yaml#/TrackerAddTask"

    /v1/tracker/tasks/list:
        $ref: "./path/tracker.yaml#/TrackerTasksList"

    /v1/tracker/tasks/info:
        $ref: "./path/tracker.yaml#/TrackerTaskInfo"

    /v1/tracker/tasks/assigned-to-user:
        $ref: "./path/tracker.yaml#/TrackerAssignedTasks"

    /v1/tracker/tasks/edit:
        $ref: "./path/tracker.yaml#/TrackerEditTasks"

    /v1/tracker/tasks/media/upload:
        $ref: "./path/tracker.yaml#/TrackerUploadMedia"


    # |--------------| TRACKER |--------------|


components:
  schemas:
    # |--------------| COMMON |--------------|


    ErrorMessage:
        $ref: "./components/common.yaml#/ErrorMessage"
    Timestamp:
        $ref: "./components/common.yaml#/Timestamp"
    Role:
        $ref: "./components/common.yaml#/Role"
    AuthorizeRequest:
        $ref: "./components/common.yaml#/AuthorizeRequest"
    AuthorizeResponse:
        $ref: "./components/common.yaml#/AuthorizeResponse"
    SuperuserCompanyAddRequest:
        $ref: "./components/common.yaml#/SuperuserCompanyAddRequest"


    # |--------------| COMMON |--------------|
    # |--------------| DOCUMENT |--------------|


    DocumentsVacationResponse:
        $ref: "./components/document.yaml#/DocumentsVacationResponse"

    DocumentSendRequest:
        $ref: "./components/document.yaml#/DocumentSendRequest"

    UploadDocumentResponse:
        $ref: "./components/document.yaml#/UploadDocumentResponse"

    DocumentsListResponse:
        $ref: "./components/document.yaml#/DocumentsListResponse"

    DocumentItem:
        $ref: "./components/document.yaml#/DocumentItem"

    DownloadDocumentResponse:
        $ref: "./components/document.yaml#/DownloadDocumentResponse"

    DocumentsListAllResponse:
        $ref: "./components/document.yaml#/DocumentsListAllResponse"

    SignItem:
        $ref: "./components/document.yaml#/SignItem"

    DocumentsGetSignsResponse:
        $ref: "./components/document.yaml#/DocumentsGetSignsResponse"

    DocumentsChainMetadataItem:
        $ref: "./components/document.yaml#/DocumentsChainMetadataItem"

    DocumentsChainUpdateRequest:
        $ref: "./components/document.yaml#/DocumentsChainUpdateRequest"

    DocumentsChainUpdateResponse:
        $ref: "./components/document.yaml#/DocumentsChainUpdateResponse"

    DocumentsChainAddRequest:
        $ref: "./components/document.yaml#/DocumentsChainAddRequest"

    UploadPhotoResponse:
        $ref: "./components/document.yaml#/UploadPhotoResponse"

    DocumentsUploadRequest:
        $ref: "./components/document.yaml#/DocumentsUploadRequest"


    # |--------------| DOCUMENT |--------------|
    # |--------------| EMPLOYEE |--------------|


    ListEmployee:
        $ref: "./components/employee.yaml#/ListEmployee"
    EmployeesResponse:
        $ref: "./components/employee.yaml#/EmployeesResponse"
    EmployeeAddRequest:
        $ref: "./components/employee.yaml#/EmployeeAddRequest"
    LoginInfo:
        $ref: "./components/employee.yaml#/LoginInfo"
    EmployeeAddHeadRequest:
        $ref: "./components/employee.yaml#/EmployeeAddHeadRequest"
    Employee:
        $ref: "./components/employee.yaml#/Employee"
    ProfileEditRequest:
        $ref: "./components/employee.yaml#/ProfileEditRequest"


    # |--------------| EMPLOYEE |--------------|
    # |--------------| MESSENGER |--------------|


    MessengerMessageContent:
        $ref: "./components/messenger.yaml#/MessengerMessageContent"

    MessengerMessage:
        $ref: "./components/messenger.yaml#/MessengerMessage"

    MessengerListedChatInfo:
        $ref: "./components/messenger.yaml#/MessengerListedChatInfo"

    MessengerListAllChats:
        $ref: "./components/messenger.yaml#/MessengerListAllChats"

    CreateChatRequest:
        $ref: "./components/messenger.yaml#/CreateChatRequest"

    CreateChatResponse:
        $ref: "./components/messenger.yaml#/CreateChatResponse"

    LoadRecentMessagesRequest:
        $ref: "./components/messenger.yaml#/LoadRecentMessagesRequest"

    # |--------------| MESSENGER |--------------|
    # |--------------| NOTIFICATION |--------------|


    NotificationsRequest:
        $ref: "./components/notification.yaml#/NotificationsRequest"
    NotificationsResponse:
        $ref: "./components/notification.yaml#/NotificationsResponse"
    Notification:
        $ref: "./components/notification.yaml#/Notification"
    ActionsRequest:
        $ref: "./components/notification.yaml#/ActionsRequest"
    ActionsResponse:
        $ref: "./components/notification.yaml#/ActionsResponse"
    UserAction:
        $ref: "./components/notification.yaml#/UserAction"


    # |--------------| NOTIFICATION |--------------|
    # |--------------| PAYMENT & ATTENDANCE |--------------|


    AbscenceType:
        $ref: "./components/payment-attendance.yaml#/AbscenceType"
    AbscenceRequestRequest:
        $ref: "./components/payment-attendance.yaml#/AbscenceRequestRequest"
    AbscenceRequestResponse:
        $ref: "./components/payment-attendance.yaml#/AbscenceRequestResponse"
    AbscenceVerdictRequest:
        $ref: "./components/payment-attendance.yaml#/AbscenceVerdictRequest"
    AbscenceSplitRequest:
        $ref: "./components/payment-attendance.yaml#/AbscenceSplitRequest"
    AbscenceSplitResponse:
        $ref: "./components/payment-attendance.yaml#/AbscenceSplitResponse"
    AbscenceRescheduleRequest:
        $ref: "./components/payment-attendance.yaml#/AbscenceRescheduleRequest"
    AbscenceRescheduleResponse:
        $ref: "./components/payment-attendance.yaml#/AbscenceRescheduleResponse"
    AttendanceAddRequest:
        $ref: "./components/payment-attendance.yaml#/AttendanceAddRequest"
    PaymentsAddBulkRequest:
        $ref: "./components/payment-attendance.yaml#/PaymentsAddBulkRequest"
    Payment:
        $ref: "./components/payment-attendance.yaml#/Payment"
    PaymentsResponse:
        $ref: "./components/payment-attendance.yaml#/PaymentsResponse"
    AttendanceListAllRequest:
        $ref: "./components/payment-attendance.yaml#/AttendanceListAllRequest"
    AttendanceListAllResponse:
        $ref: "./components/payment-attendance.yaml#/AttendanceListAllResponse"
    AttendanceListItem:
        $ref: "./components/payment-attendance.yaml#/AttendanceListItem"


    # |--------------| PAYMENT & ATTENDANCE |--------------|
    # |--------------| SEARCH & INVENTORY |--------------|


    SearchBasicRequest:
        $ref: "./components/search-inventory.yaml#/SearchBasicRequest"

    SearchFullRequest:
        $ref: "./components/search-inventory.yaml#/SearchFullRequest"

    SearchSuggestRequest:
        $ref: "./components/search-inventory.yaml#/SearchSuggestRequest"

    SearchResponse:
        $ref: "./components/search-inventory.yaml#/SearchResponse"

    InventoryItem:
        $ref: "./components/search-inventory.yaml#/InventoryItem"

    InventoryAddRequest:
        $ref: "./components/search-inventory.yaml#/InventoryAddRequest"


    # |--------------| SEARCH & INVENTORY |--------------|
    # |--------------| TRACKER |--------------|


    TrackerProjectsAddRequest:
        $ref: "./components/tracker.yaml#/TrackerProjectsAddRequest"

    TrackerProjectsListItem:
        $ref: "./components/tracker.yaml#/TrackerProjectsListItem"

    TrackerProjectsListResponse:
        $ref: "./components/tracker.yaml#/TrackerProjectsListResponse"

    TrackerTasksAddRequest:
        $ref: "./components/tracker.yaml#/TrackerTasksAddRequest"

    TrackerTasksInfoItem:
        $ref: "./components/tracker.yaml#/TrackerTasksInfoItem"

    TrackerTasksListItem:
        $ref: "./components/tracker.yaml#/TrackerTasksListItem"

    TrackerTasksListResponse:
        $ref: "./components/tracker.yaml#/TrackerTasksListResponse"

    TrackerTasksEditRequest:
        $ref: "./components/tracker.yaml#/TrackerTasksEditRequest"

    TrackerTasksMediaUploadResponse:
        $ref: "./components/tracker.yaml#/TrackerTasksMediaUploadResponse"


    # |--------------| TRACKER |--------------|
# the end :(